/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cdnfp */

#ifndef _Included_Cdnfp
#define _Included_Cdnfp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cdnfp
 * Method:    learn
 * Signature: (II)LBooleanFormula;
 */
JNIEXPORT jobject JNICALL Java_Cdnfp_learn
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
